# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :centos => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          box.vm.provision "shell", inline: <<-SHELL
#          mkdir -p ~root/.ssh
#          cp ~vagrant/.ssh/auth* ~root/.ssh
           yum install epel-release -y -q
           yum install fish -y -q
# Install tools for building rpm
           yum install rpmdevtools rpm-build -y -q
           yum install tree yum-utils mc wget gcc vim git -y -q
# Install tools for building woth mock and make prepares    
           yum install mock -y -q
           usermod -a -G mock root
# Install tools for creating your own REPO
           yum install nginx -y -q
           yum install createrepo -y -q
# HW
            adduser builder
            cd /root
            wget http://nginx.org/packages/centos/7/SRPMS/nginx-1.16.1-1.el7.ngx.src.rpm
            rpm -i nginx-1.16.1-1.el7.ngx.src.rpm
            wget https://www.openssl.org/source/openssl-1.1.1f.tar.gz
            tar -xvf openssl-1.1.1f.tar.gz 
            yum-builddep rpmbuild/SPECS/nginx.spec
            wget -O rpmbuild/SPECS/nginx.spec https://raw.githubusercontent.com/kastyle/otus/master/HW8/nginx.spec
            rpmbuild -bb rpmbuild/SPECS/nginx.spec 
            yum localinstall -y rpmbuild/RPMS/x86_64/nginx-1.16.1-1.el7.ngx.x86_64.rpm 
            systemctl start nginx
            systemctl enable nginx
            mkdir /usr/share/nginx/html/repo
            cp rpmbuild/RPMS/x86_64/nginx-1.16.1-1.el7.ngx.x86_64.rpm /usr/share/nginx/html/repo/
            wget https://www.percona.com/redir/downloads/percona-release/redhat/1.0-15/percona-release-1.0-15.noarch.rpm
            cp percona-release-1.0-15.noarch.rpm /usr/share/nginx/html/repo/
            createrepo /usr/share/nginx/html/repo/
            wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/kastyle/otus/master/HW8/default.conf
            nginx -t
            nginx -s reload
            echo '[otus]' > /etc/yum.repos.d/otus.repo
            echo 'name=otus-linux' >> /etc/yum.repos.d/otus.repo
            echo 'baseurl=http://35.228.112.147/repo/' >> /etc/yum.repos.d/otus.repo
            echo 'gpgcheck=0' >> /etc/yum.repos.d/otus.repo
            echo 'enabled=1' >> /etc/yum.repos.d/otus.repo

      SHELL

      end
  end
end
