#
PID     TTY     STAT    TIME    COMMAND
1       ?       S       9       /sbin/init
2       ?       S       0       (kthreadd)
3       ?       I       0       (rcu_gp)
4       ?       I       0       (rcu_par_gp)
6       ?       I       0       (kworker/0:0H-kblockd)
9       ?       I       0       (mm_percpu_wq)
10      ?       S       0       (ksoftirqd/0)
11      ?       I       13      (rcu_sched)
12      ?       S       0       (migration/0)
13      ?       S       0       (idle_inject/0)
14      ?       S       0       (cpuhp/0)
15      ?       S       0       (cpuhp/1)
16      ?       S       0       (idle_inject/1)
17      ?       S       0       (migration/1)
18      ?       S       0       (ksoftirqd/1)
20      ?       I       0       (kworker/1:0H-kblockd)
21      ?       S       0       (kdevtmpfs)
22      ?       I       0       (netns)
23      ?       S       0       (rcu_tasks_kthre)
24      ?       S       0       (kauditd)
25      ?       S       0       (khungtaskd)
26      ?       S       0       (oom_reaper)
27      ?       I       0       (writeback)
28      ?       S       0       (kcompactd0)
29      ?       S       0       (ksmd)
30      ?       S       0       (khugepaged)
122     ?       I       0       (kintegrityd)
123     ?       I       0       (kblockd)
124     ?       I       0       (blkcg_punt_bio)
125     ?       I       0       (tpm_dev_wq)
126     ?       I       0       (ata_sff)
128     ?       I       0       (md)
129     ?       I       0       (edac-poller)
130     ?       I       0       (devfreq_wq)
131     ?       S       0       (watchdogd)
132     ?       S       0       (irq/24-AMD-Vi)
135     ?       S       1       (kswapd0)
136     ?       I       0       (kworker/u9:0-hci0)
137     ?       S       0       (ecryptfs-kthrea)
140     ?       I       0       (kthrotld)
141     ?       I       0       (acpi_thermal_pm)
144     ?       I       0       (ipv6_addrconf)
155     ?       I       0       (kstrp)
174     ?       I       0       (charger_manager)
215     ?       S       0       (scsi_eh_0)
216     ?       I       0       (scsi_tmf_0)
219     ?       I       0       (kworker/0:1H-kblockd)
221     ?       I       0       (kworker/1:1H-kblockd)
250     ?       S       1       (jbd2/sda7-8)
251     ?       I       0       (ext4-rsv-conver)
300     ?       S       0       /lib/systemd/systemd-journald
318     ?       S       0       /lib/systemd/systemd-udevd
327     ?       S       0       (loop0)
343     ?       S       0       (loop1)
347     ?       S       0       (loop2)
348     ?       S       0       (loop3)
349     ?       S       0       (loop4)
351     ?       S       0       (loop5)
355     ?       S       0       (loop6)
357     ?       S       0       (loop7)
359     ?       S       0       (loop8)
361     ?       S       0       (loop9)
362     ?       S       0       (loop10)
364     ?       S       0       (loop11)
365     ?       S       0       (loop12)
367     ?       S       0       (loop13)
370     ?       S       0       (loop14)
372     ?       S       0       (loop15)
384     ?       I       0       (cfg80211)
388     ?       S       1       (irq/31-ELAN0622)
389     ?       I       0       (amd_iommu_v2)
422     ?       I       0       (ttm_swap)
429     ?       S       57      (gfx)
431     ?       S       0       (comp_1.0.0)
434     ?       S       0       (comp_1.0.1)
435     ?       S       0       (comp_1.0.2)
436     ?       S       0       (comp_1.0.3)
437     ?       S       0       (comp_1.0.4)
438     ?       I       0       (cryptd)
439     ?       S       0       (comp_1.0.5)
440     ?       S       0       (comp_1.0.6)
442     ?       S       0       (comp_1.0.7)
445     ?       S       7       (sdma0)
446     ?       S       0       (uvd)
450     ?       S       0       (vce0)
453     ?       S       0       (vce1)
529     ?       I       0       (kworker/u9:2-hci0)
779     ?       S       1       /lib/systemd/systemd-resolved
780     ?       S       0       /lib/systemd/systemd-timesyncd
845     ?       S       0       /usr/bin/python3
846     ?       S       0       /usr/lib/accountsservice/accounts-daemon
847     ?       S       0       /lib/systemd/systemd-logind
848     ?       S       0       /usr/sbin/cron
869     ?       S       2       /usr/bin/dbus-daemon
892     ?       S       0       /sbin/wpa_supplicant
894     ?       S       3       /usr/sbin/NetworkManager
897     ?       S       1       /usr/lib/udisks2/udisksd
905     ?       S       0       /usr/sbin/irqbalance
908     ?       S       3       /usr/lib/snapd/snapd
909     ?       S       0       /usr/sbin/rsyslogd
910     ?       S       0       avahi-daemon:
911     ?       S       0       /usr/lib/bluetooth/bluetoothd
912     ?       S       0       /usr/sbin/smartd
920     ?       S       0       avahi-daemon:
921     ?       S       0       /usr/sbin/acpid
928     ?       S       0       /usr/sbin/ModemManager
954     ?       S       0       /usr/lib/policykit-1/polkitd
984     ?       S       0       /usr/bin/python3
998     ?       S       0       /usr/sbin/gdm3
1005    ?       S       0       gdm-session-worker
1006    ?       S       2       (RTW_CMD_THREAD)
1012    ?       I       0       (iprt-VBoxWQueue)
1017    ?       S       0       (iprt-VBoxTscThr)
1024    ?       S       0       /lib/systemd/systemd
1025    ?       S       0       (sd-pam)
1060    ?       S       0       /usr/lib/gdm3/gdm-wayland-session
1064    ?       S       0       /usr/bin/dbus-daemon
1072    ?       S       0       /usr/lib/gnome-session/gnome-session-binary
1083    ?       S       29      /usr/bin/gnome-shell
1112    ?       S       3       /usr/lib/upower/upowerd
1143    ?       S       0       /usr/bin/Xwayland
1153    ?       S       0       /usr/lib/at-spi2-core/at-spi-bus-launcher
1158    ?       S       0       /usr/bin/dbus-daemon
1160    ?       S       0       /usr/lib/at-spi2-core/at-spi2-registryd
1163    ?       S       0       /usr/bin/pulseaudio
1165    ?       S       0       /usr/lib/rtkit/rtkit-daemon
1177    ?       S       0       ibus-daemon
1180    ?       S       0       /usr/lib/ibus/ibus-dconf
1183    ?       S       0       /usr/lib/ibus/ibus-x11
1185    ?       S       0       /usr/lib/ibus/ibus-portal
1194    ?       S       0       /usr/libexec/xdg-permission-store
1202    ?       S       0       /usr/lib/x86_64-linux-gnu/boltd
1203    ?       S       13      /usr/lib/packagekit/packagekitd
1210    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-xsettings
1213    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-a11y-settings
1214    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-clipboard
1217    ?       S       2       /usr/lib/gnome-settings-daemon/gsd-color
1219    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-datetime
1220    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-housekeeping
1221    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-keyboard
1225    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-media-keys
1226    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-mouse
1227    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-power
1229    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-print-notifications
1233    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-rfkill
1234    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
1237    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-sharing
1243    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-smartcard
1244    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-sound
1246    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-wacom
1260    ?       S       0       /usr/lib/ibus/ibus-engine-simple
1324    ?       S       0       /usr/lib/colord/colord
1340    ?       S       0       /usr/bin/whoopsie
1354    ?       S       0       /usr/sbin/kerneloops
1362    ?       S       0       /usr/sbin/kerneloops
1386    ?       S       0       gdm-session-worker
1389    ?       S       0       /lib/systemd/systemd
1390    ?       S       0       (sd-pam)
1403    ?       S       0       /usr/bin/gnome-keyring-daemon
1407    tty2    S       0       /usr/lib/gdm3/gdm-x-session
1409    tty2    S       352     /usr/lib/xorg/Xorg
1426    ?       S       1       /usr/bin/dbus-daemon
1429    ?       S       0       /usr/lib/gnome-session/gnome-session-binary
1524    ?       S       0       /usr/bin/ssh-agent
1527    ?       S       0       /usr/lib/gvfs/gvfsd
1532    ?       S       0       /usr/lib/gvfs/gvfsd-fuse
1545    ?       S       0       /usr/lib/at-spi2-core/at-spi-bus-launcher
1550    ?       S       0       /usr/bin/dbus-daemon
1553    ?       S       2       /usr/lib/at-spi2-core/at-spi2-registryd
1572    ?       S       488     /usr/bin/gnome-shell
1587    ?       S       1       /usr/bin/pulseaudio
1599    ?       S       0       (krfcommd)
1600    ?       S       24      ibus-daemon
1604    ?       S       0       /usr/lib/ibus/ibus-dconf
1608    ?       S       0       /usr/lib/ibus/ibus-x11
1611    ?       S       0       /usr/lib/ibus/ibus-portal
1615    ?       S       0       /usr/libexec/xdg-permission-store
1623    ?       S       0       /usr/lib/gnome-shell/gnome-shell-calendar-server
1627    ?       S       0       /usr/lib/evolution/evolution-source-registry
1635    ?       S       0       /usr/lib/gnome-online-accounts/goa-daemon
1645    ?       S       0       /usr/lib/gnome-online-accounts/goa-identity-service
1652    ?       S       0       /usr/lib/gvfs/gvfs-udisks2-volume-monitor
1656    ?       S       0       /usr/lib/gvfs/gvfs-goa-volume-monitor
1660    ?       S       0       /usr/lib/gvfs/gvfs-mtp-volume-monitor
1664    ?       S       0       /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
1668    ?       S       0       /usr/lib/gvfs/gvfs-afc-volume-monitor
1675    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-power
1678    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-print-notifications
1680    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-rfkill
1682    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy
1684    ?       S       1       /usr/lib/gnome-settings-daemon/gsd-sharing
1691    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-xsettings
1699    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-smartcard
1703    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-sound
1707    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-wacom
1712    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-a11y-settings
1713    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-clipboard
1714    ?       S       2       /usr/lib/gnome-settings-daemon/gsd-color
1717    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-datetime
1718    ?       S       1       /usr/lib/gnome-settings-daemon/gsd-housekeeping
1719    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-keyboard
1720    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-media-keys
1723    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-mouse
1746    ?       S       0       /usr/lib/gnome-settings-daemon/gsd-printer
1774    ?       S       0       /usr/lib/gnome-disk-utility/gsd-disk-utility-notify
1780    ?       S       14      nautilus-desktop
1796    ?       S       0       /usr/lib/gvfs/gvfsd-trash
1813    ?       S       0       /usr/lib/evolution/evolution-calendar-factory
1824    ?       S       0       /usr/lib/dconf/dconf-service
1829    ?       S       0       /usr/lib/evolution/evolution-calendar-factory-subprocess
1832    ?       S       5       /usr/lib/ibus/ibus-engine-simple
1848    ?       S       0       /usr/lib/evolution/evolution-addressbook-factory
1859    ?       S       0       /usr/lib/evolution/evolution-addressbook-factory-subprocess
1897    ?       S       0       /usr/lib/gvfs/gvfsd-metadata
1950    ?       S       0       /sbin/dhclient
2036    ?       S       5       /usr/bin/gnome-software
2038    ?       S       0       update-notifier
2074    ?       S       1       /usr/lib/fwupd/fwupd
2153    ?       S       0       /usr/lib/deja-dup/deja-dup-monitor
2188    ?       S       596     /opt/google/chrome/chrome
2195    ?       S       0       cat
2196    ?       S       0       cat
2199    ?       S       0       /opt/google/chrome/chrome
2200    ?       S       0       /opt/google/chrome/nacl_helper
2203    ?       S       0       /opt/google/chrome/chrome
2221    ?       S       396     /opt/google/chrome/chrome
2226    ?       S       61      /opt/google/chrome/chrome
2280    ?       S       37      /opt/google/chrome/chrome
2336    ?       S       8       /opt/google/chrome/chrome
2533    ?       S       52      /home/kastyle/.dropbox-dist/dropbox-lnx.x86_64-92.4.382/dropbox
2722    ?       S       0       /usr/sbin/uuidd
3118    ?       S       0       /opt/google/chrome/chrome
3132    ?       S       0       /opt/google/chrome/chrome
3500    ?       S       91      /usr/share/code/code
3503    ?       S       0       /usr/share/code/code
3528    ?       S       230     /usr/share/code/code
3550    ?       S       510     /usr/share/code/code
3587    ?       S       11      /usr/share/code/code
3588    pts     S       0       /bin/bash
3616    ?       S       5       /usr/share/code/code
3692    ?       S       24      /usr/lib/gnome-terminal/gnome-terminal-server
3702    pts     S       0       bash
4049    ?       S       0       /usr/lib/gvfs/gvfsd-network
4070    ?       S       0       /usr/lib/gvfs/gvfsd-dnssd
6020    ?       S       0       /usr/sbin/cupsd
6021    ?       S       0       /usr/sbin/cups-browsed
14823   ?       I       0       (kworker/0:0-events)
14824   ?       I       0       (kworker/1:0-events)
21380   ?       I       2       (kworker/u8:0-events_unbound)
21407   ?       S       0       /usr/lib/libreoffice/program/oosplash
21423   ?       S       12      /usr/lib/libreoffice/program/soffice.bin
26747   ?       I       0       (kworker/u8:2+events_unbound)
26750   ?       I       0       (kworker/0:2-events)
26753   ?       I       0       (kworker/1:1-events)
26914   ?       I       0       (kworker/u8:1)
31306   ?       I       0       (kworker/1:2-events)
31308   ?       I       0       (kworker/0:1-events)
31309   ?       S       3       /opt/google/chrome/chrome
31341   ?       S       0       /opt/google/chrome/chrome
31357   pts     S       0       /bin/bash
